name: smoke

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feat/**, fix/** ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Import smoke
        run: |
          python - <<'PY'
          import importlib
          for m in ("main", "deepseek_enrichment", "app"):
              importlib.import_module(m)
              print(m, "OK")
          PY

      - name: UI headless smoke
        run: |
          python scripts/ui_smoke.py
